# Setup
title:               Random Notes
tagline:             'by Hans Montañana'
description:         

paginate:            5
permalink:           pretty


# urls
url: https://javiermontanana.com
baseurl: /randomnotes



# About/contact
author:
  name:              Hans Montañana
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
